import { baseApi } from "@/redux/store/baseApi";

// --- Types & Interfaces ---

export interface ClockInUser {
  id: number;
  name: string;
  email: string;
  role: string;
}

export interface ClockInQrSession {
  id: number;
  token: string;
  refresh_interval: number;
  interval_display: string;
  created_at: string;
  expires_at: string;
}

// --- Response Interfaces ---

interface ClockInQrResponse {
  message: string;
  location: string;
  user: ClockInUser;
  qr_session: ClockInQrSession;
  seconds_left: number;
}

// --- API Slice ---

export const clockInApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * GET: Get QR generated code with clock-in auth
     * Based on Image: /api/admin/clock-in/qr/
     */
    getClockInQr: builder.query<ClockInQrResponse, void>({
      query: () => "/admin/clock-in/qr/",
      // We use the same tag as the admin to ensure that if a QR is
      // regenerated by an admin, the user's view can be updated.
      providesTags: ["AdminQrSession"],
    }),
  }),
});

export const { useGetClockInQrQuery } = clockInApi;
